// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwfttcbnlyqhwsydmete.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3ZnR0Y2JubHlxaHdzeWRtZXRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Mjc5NTcsImV4cCI6MjA3MTUwMzk1N30.-00uefs2ZHxpCcxlzVFo3l6jgVq8LACN0yEr0BuPJuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});